#########################################################
apiVersion: v1
kind: Service
metadata:
  name: golang-gin
  labels:
    app: golang-gin
    tier: backend
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - targetPort: 8080
    port: 80
  selector:
    app: golang-gin
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-gin
  labels:
    app: golang-gin
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-gin
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: golang-gin
        tier: backend
        version: "0"
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: cloud.google.com/gke-preemptible
      #           operator: DoesNotExist
      containers:
        - name: golang-gin
          image: gcr.io/kubernetes-271106/golang-gin:latest
          imagePullPolicy: Always
          env:
            - name: LINES
              value: "42"
            - name: COLUMNS
              value: "178"
          ports:
            - containerPort: 8080
          livenessProbe:
              httpGet:
                path: /api/ping
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 5
              periodSeconds: 30
          readinessProbe:
              httpGet:
                path: /api/ping
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 60
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 10
